
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.98.189.129:3306/mall?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.mapper: DEBUG
#
dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://47.98.189.129:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.serviceImpl

server:
  port: 9090
